apiVersion: apps/v1
kind: Deployment

metadata:
  name: php-local

spec:
  replicas: 2

  selector:
    matchLabels:
      app: php-local

  template:
    metadata:
      labels:
        app: php-local

    spec:
      containers:
      - name: php-local
        image: 172.17.0.4:8082/php-local:latest

        ports:
        - containerPort: 80

